name: Greetings
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:

  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment for issue
      if: github.event_name =='issues' 
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.issue.number)}}
        body: |
            @${{ github.actor }}, thanks for your issue on this repo, we'll check this soon
    - name: Create comment for PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.number)}}
        body: |
            @${{ github.actor }}, thanks for your PR on this repo, we'll check this soon